FROM amazonlinux:latest

RUN yum install -y java-11-amazon-corretto.x86_64

ENV APP_HOME=/workspace
ENV JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto.x86_64
WORKDIR $APP_HOME
COPY build.gradle settings.gradle gradlew $APP_HOME/
COPY ./ $APP_HOME
RUN ./gradlew test
RUN ./gradlew build

# recommended by spring boot
VOLUME /tmp

# jar target
ENV JAR_TARGET "circleci-test-project-local-0.0.1-SNAPSHOT.jar"

# set entrypoint to execute spring boot application
ENTRYPOINT ["sh","-c","java -jar -Dspring.profiles.active=docker build/libs/${JAR_TARGET}"]