spring:
  profiles:
    active: localhost
---
spring:
  datasource:
    url: "jdbc:mysql://test-database-1.c6xeb2zudz8s.ap-northeast-1.rds.amazonaws.com:3306/api_sample?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 10113-Xavi
  jpa:
    show-sql: true
    database-platform : org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: create
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    EnumType: trace
                    descriptor:
                        sql:
                            BasicBinder: TRACE
---
spring:
  profiles: docker
  datasource:
    url: "jdbc:mysql://dbserver/api_sample?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 10113-Xavi
  jpa:
    show-sql: true
    database-platform : org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: create