version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.2
jobs:
  deploy:
    machine:
      image: circleci/classic:edge
    steps: 
        - checkout 
        - add_ssh_keys # 秘密鍵を読み込む
        - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /home/ec2-user/src/circleci-test-project/ && git pull && ./gradlew build && java -jar ./build/libs/circleci-test-project-local-0.0.1-SNAPSHOT.jar' 

workflows:
  version: 2.1
  test-build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: DockerFile
          path: .
          region: AWS_REGION
          repo: circleci-test-project
          tag: "$CIRCLE_SHA1"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          aws-region: ${AWS_REGION}
          family: "circleci-ecs-service"
          cluster-name: "circleci-ecs"
          container-image-name-updates: "container=circleci-ecs-service,tag=${CIRCLE_SHA1}"
      - deploy:
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: main