version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  test:
    docker:
      - image: ouinaka/amazonlinux:custom
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-amazon-corretto.x86_64
      JAVA_OPTS: -Xmx3200m
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps: 
      - checkout 
      - run: 
          name: テストの実施
          command: ./gradlew test
  build:
    docker:
      - image: ouinaka/amazonlinux:custom
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-amazon-corretto.x86_64
      JAVA_OPTS: -Xmx3200m
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps: 
      - checkout 
      - run: 
          name: ビルドの実施
          command: ./gradlew build
  # deploy ジョブ: EC2 に SSH 接続して、デプロイを実行する
  deploy:
      machine:
          image: circleci/classic:edge
      steps:
          - checkout
          # CircleCI に登録した秘密鍵を呼び出す
          - add_ssh_keys:
          # CircleCI に登録した環境変数を使って SSH
          - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /home/ec2-user/src && git pull'

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
              - build
          filters:
              branches:
                  only: main