version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps: 
      - checkout 
      # 依存関係をダウンロードしてキャシュする
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}
          - v1-dependencies-{{ .Branch }}-
          - v1-dependencies-
      - run:
          name: docker-compose pull
          command: docker-compose pull
      - run:
          name: docker-compose build and up
          command: docker-compose up -d mysql
      - run: gradle dependencies
      - run: gradle build -x test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}
      - run: 
          name: テストの実施
          command: gradle test
