version: 2.1
jobs:
  build:
    docker:
      - image: ouinaka/amazonlinux:custom
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-amazon-corretto.x86_64
      JAVA_OPTS: -Xmx3200m
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps: 
      - checkout 
      - setup_remote_docker:
          version: 19.03.8
          docker_layer_caching: true
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}
          - v1-dependencies-{{ .Branch }}-
          - v1-dependencies-
      - run: 
          name: テストの実施
          command: ./gradlew test
