version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build-and-test:
    docker:
      - image: ouinaka/amazonlinux:custom
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-amazon-corretto.x86_64
      JAVA_OPTS: -Xmx3200m
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps: 
      - checkout 
      - run: 
          name: テストの実施
          command: ./gradlew test
      - run: 
          name: ビルドの実施
          command: ./gradlew build

  deploy:
    machine:
      image: circleci/classic:edge
    steps: 
        - checkout 
        - add_ssh_keys # 秘密鍵を読み込む
        - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /home/ec2-user/src && git pull' 

workflows:
  version: 2.1
  test-build-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main