version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
  aws-ecr: circleci/aws-ecr@6.15.2
jobs:
  deploy:
    machine:
      image: circleci/classic:edge
    steps: 
        - checkout 
        - add_ssh_keys # 秘密鍵を読み込む
        - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /home/ec2-user/src/circleci-test-project/ && git pull && ./gradlew build && java -jar ./build/libs/circleci-test-project-local-0.0.1-SNAPSHOT.jar' 

workflows:
  version: 2.1
  test-build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: ECR_ACCOUNT_URL
          aws-access-key-id: ECR_AWS_ACCESS_KEY_ID
          aws-secret-access-key: ECR_AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: ECR_REGION
          repo: circleci-test-project
          tag: "$CIRCLE_SHA1"
      - deploy:
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: main